question_data = [
        {
            "category": "Entertainment: Television",
            "type": "boolean", "difficulty": "medium",
            "question": "Rick, Carl, Daryl, Morgan, Carol and Maggie were introduced to us in Season 1.",
            "correct_answer": "False",
            "incorrect_answers": ["True"]
        },
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "Super Mario Bros. was released in 1990.", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "Furby was released in 1998.", "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The average woman is 5 inches 13 centimeters shorter than the average man.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
         "question": "The French word to travel is Travail", "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "In the game Subnautic, a Cave Crawler will attack you.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
         "question": "Early RAM was directly seated onto the motherboard and could not be easily removed.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
         "question": "Nick Mason is the only member to appear on every Pink Floyd album.", "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "medium",
         "question": "In To Love-Ru: Darkness, Yami reveals her real name is Eve.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
         "question": "The character that would eventually become Dr. Eggman was considered for "
                     "the role of Sega&#039;s new flagship mascot before Sonic was.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
         "question": "The most frequent subconscious activity repeated by the human body is blinking.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Entertainment: Books", "type": "boolean", "difficulty": "medium",
         "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
         "correct_answer": "True", "incorrect_answers": ["False"]}
]
